name: CICD for Group 2 Chat Application - Development
run-name: ${{ github.actor }} is running CICD for Group 2 Chat Application - Development

# The workflow is triggered on push event to the 'dev' branch
on:
  push:
    branches: [ dev ]
  
# Define permissions for this workflow, which can be added at either the job or workflow level.      
permissions:
  id-token: write # This is required for requesting the JWT.
  actions: read # Permission to read actions.
  contents: read # Permission to read contents.
  security-events: write # Grants permission to write security event data for the repository.


jobs:

  # The pre-deploy job just prints the type of event and branch that triggered the workflow
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event_name }} event on ${{ github.ref_name }} branch."

  # This job is responsible for running unit tests on the application
  unit-testing:
    runs-on: ubuntu-latest
    needs: pre-deploy
    name: Unit Testing
    steps:
       # Checkout the latest code from the repository.
      - name: Checkout repo code
        uses: actions/checkout@v3
       # Install the required npm dependencies for the application
      - name: Install dependencies
        run: npm install
      # Execute unit tests using npm test
      - name: Run unit tests
        run: npm test

  #SNYK-Comprehensive-Security-scan is conducting a comprehensive set of security tests, including Snyk Code(SAST), Snyk Open Source(SCA), Snyk Infrastructure as Code, and Snyk Container tests         
  SNYK-Comprehensive-Security-scan:
    needs: pre-deploy
    uses: ./.github/workflows/snyk-security.yml
    secrets: inherit
   
  # This job handles deployment to the development environment
  deploy:
    runs-on: ubuntu-latest
    outputs:
      access_url_output: ${{ steps.tf-outputs.outputs.access_url }} # Define outputs for this job which can be used in subsequent jobs.
    needs: [ pre-deploy, unit-testing, SNYK-Comprehensive-Security-scan ] # This job depends on the completion of 'pre-deploy', 'unit-testing' and "SNYK-Comprehensive-Security-scan" jobs
    name: Deploy to AWS
    # Set environment variables for this job. Here, the deployment environment is set based on the branch name 'dev'.
    env:
      environment: ${{ github.ref_name }} # Specify the environment to deploy
    steps:
      
      # Checkout the latest code from the repository
      - name: Checkout repo code
        uses: actions/checkout@v3
      
      # Set up AWS credentials by using OIDC authentication which are stored in the Github Actions Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEV_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # Log in to Amazon ECR (Elastic Container Registry)
      - name: Login to Amazon ECR 
        id: login-ecr # Define an id which allows other steps to reference outputs from this step.
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      # Create an ECR repository using Terraform and output the repository url for the input to the subsequent steps.
      - name: Create ECR repository using Terraform
        id: terraform-ecr # Define an id which allows other steps to reference outputs from this step.
        working-directory: ./modules/ecr
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
          echo "ecr_url=$(terraform output -json | jq -r .repository_url.value)" >> $GITHUB_OUTPUT
      
      # Build and push the Docker image to the Amazon ECR Repository using the repository url from the previous step.
      - name: Push image to Amazon ECR
        id: push-image  # Define an id which allows other steps to reference outputs from this step.
        env:
          image_tag: latest # Define the image tag
        run: |
          docker build -t ${{ steps.terraform-ecr.outputs.ecr_url }}:$image_tag .
          docker push ${{ steps.terraform-ecr.outputs.ecr_url }}:$image_tag
      
      # Retrieve the digest of the pushed Docker image from ECR using Terraform
      - name: Retrieve ECR Image Digest
        id: get-image-digest  # Define an id for this step to be used in the subsequent steps.
        working-directory: ./modules/ecr  # Set the working directory for this step
        # Run Terraform's 'apply' command with the '-refresh-only' option to get the latest state without making any changes.
        # Terraform's 'output' command is used to fetch the image digest value and then store it in an output variable for later use.
        run: |
          terraform apply -auto-approve -refresh-only
          echo "image_digest=$(terraform output -json | jq -r .image_digest.value)" >> $GITHUB_OUTPUT

      # Use Terraform to create AWS ECS resources like cluster, task definition, and service
      - name: Create AWS ECS cluster, task definition and service using Terraform
        working-directory: ./environments/${{ env.environment }}  # Set the working directory for this step
        # 'terraform apply -auto-approve' command is used to create or update the resources with auto-approval.
        # Various input variables are passed using the '-var' option. These are used to customize the Terraform configuration.
        # The '-target' option is used to restrict the scope of resource application.
        run: |
          terraform init
          terraform apply -auto-approve \
          -var "image_name=${{ steps.terraform-ecr.outputs.ecr_url }}" \
          -var "image_digest=${{ steps.get-image-digest.outputs.image_digest }}" \
          -target="aws_ecs_cluster.cluster" -target="aws_ecs_task_definition.task" \
          -target="aws_security_group.ecs_sg" -target="aws_ecs_service.service"
      
      # Retrieve the access URL from Terraform outputs
      - name: Set up Terraform outputs
        id: tf-outputs  # Define an id for this step to be used in the subsequent steps.
        working-directory: ./environments/${{ env.environment }}  # Set the working directory for this step
        # Apply the Terraform configuration which includes the data block in the output.tf file.
        # Various input variables are passed using the '-var' option. These are used to customize the Terraform configuration.
        # Fetch the 'all_access_urls' output from Terraform and process it with 'jq' to retrieve the access URL.
        run: |
          terraform apply -auto-approve \
          -var "image_name=${{ steps.terraform-ecr.outputs.ecr_url }}" \
          -var "image_digest=${{ steps.get-image-digest.outputs.image_digest }}"
          echo "access_url=$(terraform output -json all_access_urls | jq -r 'to_entries[0].value')" >> $GITHUB_OUTPUT

      # Display the access URL in the GitHub Actions log
      - name: Echo Access URL 
        run: echo "The Access URL is ${{ steps.tf-outputs.outputs.access_url }}"

  # This GitHub Actions workflow job is named 'zap-scan' and is responsible for performing an OWASP ZAP Full Scan,
  # which is a Dynamic Application Security Testing (DAST) scan.
  zap-scan:
    # It runs on the 'ubuntu-latest' runner with necessary permissions granted for the scan.
    runs-on: ubuntu-latest
    permissions: write-all
    # This job depends on the successful completion of the 'deploy' job before it can run.
    needs: deploy
    # Name of the job, indicating it's an OWASP ZAP Full Scan.
    name: OWASP ZAP Full Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          # The 'target' parameter specifies the URL of the deployed application to be scanned.
          target: ${{ needs.deploy.outputs.access_url_output }}