name: CICD for Group 2 Chat Application - Development
run-name: ${{ github.actor }} is running CICD for Group 2 Chat Application - Development

# The workflow is triggered on push event to the 'dev' branch
on:
  push:
    branches: [ dev ]
  
# Define permissions for this workflow, which can be added at either the job or workflow level.      
permissions:
  id-token: write # This is required for requesting the JWT.
  actions: read # Permission to read actions.
  contents: read # Permission to read contents.
  security-events: write # Grants permission to write security event data for the repository.


jobs:

  # The pre-deploy job just prints the type of event and branch that triggered the workflow
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event_name }} event on ${{ github.ref_name }} branch."

  # This job is responsible for running unit tests on the application
  unit-testing:
    runs-on: ubuntu-latest
    needs: pre-deploy
    name: Unit Testing
    steps:
       # Checkout the latest code from the repository.
      - name: Checkout repo code
        uses: actions/checkout@v3
       # Install the required npm dependencies for the application
      - name: Install dependencies
        run: npm install
      # Execute unit tests using npm test
      - name: Run unit tests
        run: npm test

  #SNYK-Comprehensive-Security-scan is conducting a comprehensive set of security tests, including Snyk Code(SAST), Snyk Open Source(SCA), Snyk Infrastructure as Code, and Snyk Container tests         
  SNYK-Comprehensive-Security-scan:
    needs: pre-deploy
    uses: ./.github/workflows/snyk-security.yml
    secrets: inherit
   
  # This job handles deployment to the development environment
  deploy:
    runs-on: ubuntu-latest
    outputs:
      access_url_output: ${{ steps.tf-outputs.outputs.access_url }} # Define outputs for this job which can be used in subsequent jobs.
    needs: [ pre-deploy, unit-testing, SNYK-Comprehensive-Security-scan ] # This job depends on the completion of 'pre-deploy', 'unit-testing' and "SNYK-Comprehensive-Security-scan" jobs
    name: Deploy to AWS
    # Set environment variables for this job. Here, the deployment environment is set based on the branch name 'dev'.
    env:
      environment: ${{ github.ref_name }} # Specify the environment to deploy
    steps:
      
      # Checkout the latest code from the repository
      - name: Checkout repo code
        uses: actions/checkout@v3
      
      # Set up AWS credentials by using OIDC authentication which are stored in the Github Actions Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEV_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # Log in to Amazon ECR (Elastic Container Registry)
      - name: Login to Amazon ECR 
        id: login-ecr # Define an id which allows other steps to reference outputs from this step.
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      # Create an ECR repository using Terraform and output the repository url for the input to the subsequent steps.
      - name: Create ECR repository using Terraform
        id: terraform-ecr # Define an id which allows other steps to reference outputs from this step.
        working-directory: ./modules/ecr
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
          echo "ecr_url=$(terraform output -json | jq -r .repository_url.value)" >> $GITHUB_OUTPUT
      
      # Build and push the Docker image to the Amazon ECR Repository using the repository url from the previous step.
      - name: Push image to Amazon ECR
        id: push-image  # Define an id which allows other steps to reference outputs from this step.
        env:
          image_tag: latest # Define the image tag
        run: |
          docker build -t ${{ steps.terraform-ecr.outputs.ecr_url }}:$image_tag .
          docker push ${{ steps.terraform-ecr.outputs.ecr_url }}:$image_tag

      # Use Terraform to create AWS ECS resources like cluster, task definition, and service
      - name: Create AWS ECS cluster, task definition and service using Terraform
        id: terraform-ecs # Define an id which allows other steps to reference outputs from this step.
        working-directory: ./environments/${{ env.environment }}  # Set the working directory for this step
        # 'terraform apply -auto-approve' command is used to create or update the resources with auto-approval.
        # Variables are passed using the '-var' option to customize the Terraform configuration.
        # The '-target' option is used to restrict the scope of resource application.
        # Mark the ECS service resource for recreation in the next Terraform apply.
        run: |
          terraform init
          terraform apply -auto-approve \
          -var "image_name=${{ steps.terraform-ecr.outputs.ecr_url }}" \
          -target="aws_ecs_cluster.cluster" -target="aws_ecs_task_definition.task" \
          -target="aws_security_group.ecs_sg" -target="aws_ecs_service.service"
          terraform taint aws_ecs_service.service

          # Output the ECS cluster name for use in subsequent steps.
          echo "ecs_name=$(terraform output -json | jq -r .ecs_name.value)" >> $GITHUB_OUTPUT
      
      # Ensure that ECS task is running before proceeding to next step.
      - name: Check if ECS task is running
        run: |
          # Define ECS cluster and service names based on previous Terraform outputs.
          cluster_name=${{ steps.terraform-ecs.outputs.ecs_name}}
          service_name="${{ steps.terraform-ecs.outputs.ecs_name}}-service"
        
          # Set a timeout and interval for checking task status
          timeout=600 # Wait for 10 minutes max
          interval=30 # Check every 30 seconds
        
          # Capture the start time for timeout tracking
          start_time=$(date +%s)
        
          # Begin loop to check task status
          while true; do
              # Calculate elapsed time
              current_time=$(date +%s)
              elapsed_time=$((current_time - start_time))
                       
              # Fetch the task ARNs associated with the service
              task_arns=$(aws ecs list-tasks --cluster $cluster_name --service-name $service_name --query "taskArns" --output text)
                       # If no tasks are found, wait for the interval duration and then check again
              if [ -z "$task_arns" ]; then
                  echo "No tasks found. Waiting..."
                  sleep $interval
                  continue
              fi
        
              # Fetch the last status of the tasks
              statuses=$(aws ecs describe-tasks --cluster $cluster_name --tasks $task_arns --query "tasks[*].lastStatus" --output text)
        
              # Start by assuming all tasks are in the "RUNNING" state.
              all_running=true
        
              # Loop through each status and check if it's "RUNNING"
              for status in $statuses; do
                  if [ "$status" != "RUNNING" ]; then
                      all_running=false
                      break
                  fi
              done
        
              # If all tasks are running, exit the loop
              if $all_running; then
                  echo "All tasks are running."
                  break
              fi
        
              # If timeout is reached before all tasks are running, exit with an error
              if [[ $elapsed_time -ge $timeout ]]; then
                  echo "Timeout reached before all tasks reached RUNNING state."
                  exit 1
              fi
        
              # Wait for the specified interval before checking again
              echo "Waiting for tasks to reach RUNNING state..."
              sleep $interval
          done

      # Retrieve the access URL from Terraform outputs
      - name: Set up Terraform outputs
        id: tf-outputs  # Define an id for this step to be used in the subsequent steps.
        working-directory: ./environments/${{ env.environment }}  # Set the working directory for this step
        # Apply the Terraform configuration with the '-refresh-only' option to only refresh the state without creating/updating any resources.
        # Iinput variables are passed using the '-var' option. These are used to customize the Terraform configuration.
        # Fetch the 'all_access_urls' output from Terraform and process it with 'jq' to retrieve the access URL.
        run: |
          terraform apply -refresh-only -auto-approve -var "image_name=${{ steps.terraform-ecr.outputs.ecr_url }}"
          echo "access_url=$(terraform output -json all_access_urls | jq -r 'to_entries[0].value')" >> $GITHUB_OUTPUT

      # Display the access URL in the GitHub Actions log
      - name: Echo Access URL 
        run: echo "The Access URL is ${{ steps.tf-outputs.outputs.access_url }}"

  # This GitHub Actions workflow job is named 'zap-scan' and is responsible for performing an OWASP ZAP Full Scan,
  # which is a Dynamic Application Security Testing (DAST) scan.
  zap-scan:
    # It runs on the 'ubuntu-latest' runner with necessary permissions granted for the scan.
    runs-on: ubuntu-latest
    permissions: write-all
    # This job depends on the successful completion of the 'deploy' job before it can run.
    needs: deploy
    # Name of the job, indicating it's an OWASP ZAP Full Scan.
    name: OWASP ZAP Full Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          # The 'target' parameter specifies the URL of the deployed application to be scanned.
          target: ${{ needs.deploy.outputs.access_url_output }}