name: SCA for Nodejs Application with Docker
run-name: ${{ github.actor }} is running CICD for Nodejs Application with Docker

on:
  push:
    branches: 
      - feature-wengsiong-sca

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    name: Open Source Security Scan
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: Run Snyk to scan for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called even if Snyk fails
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --severity-threshold=high --sarif-file-output=snyk.sarif
      - name: Code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Monitor for vulnerabilities continuously
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
