name: CICD for Group 2 Chat Application
run-name: ${{ github.actor }} is running CICD for Group 2 Chat Application


on:
  pull_request:
    branches: [ stage ]

# Define permissions for this workflow, which can be added at either the job or workflow level.      
permissions:
  id-token: write # This is required for requesting the JWT
  actions: read
  contents: read
  security-events: write


jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event_name }} event."