name: DAST using ZAP
run-name: ${{ github.actor }} is running ZAP Action Full Scan

on:
  schedule:
    # Runs every day At 01:00.
    - cron:  '1 4 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://www.zaproxy.org/'