name: DAST for Nodejs Application with Docker
run-name: ${{ github.actor }} is running DAST for Nodejs Application with Docker

on:
  push:
    branches: 
      - chris

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: 'https://www.zaproxy.org/'